services:
  - type: web
    name: my-notes
    runtime: node
    buildCommand: npm install && npm --prefix server install && npm run build
    startCommand: npm --prefix server start
    plan: free
    autoDeploy: true
